import 'package:hive/hive.dart';

part 'message_model.g.dart'; // Generated by Hive code generation

@HiveType(typeId: 0)
class MessageModel extends HiveObject {
  @HiveField(0)
  final String content;
  @HiveField(1)
  final bool isSentByUser;

  MessageModel({required this.content, required this.isSentByUser});
}
