// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirddingF8ISnefovORmNVI_24Bbc6tW0',
    appId: '1:183778840538:web:363210893cb742fdc7bae3',
    messagingSenderId: '183778840538',
    projectId: 'ayna-c7a1e',
    authDomain: 'ayna-c7a1e.firebaseapp.com',
    storageBucket: 'ayna-c7a1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtksdZgTK-6zRGRE9cOt-riYxreuu5tw',
    appId: '1:183778840538:android:f9079eeef30aaaefc7bae3',
    messagingSenderId: '183778840538',
    projectId: 'ayna-c7a1e',
    storageBucket: 'ayna-c7a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4dSlemipM6XKoURyqWtuYlsDP4dcxQq8',
    appId: '1:183778840538:ios:fa23c8efc7f7e6ccc7bae3',
    messagingSenderId: '183778840538',
    projectId: 'ayna-c7a1e',
    storageBucket: 'ayna-c7a1e.appspot.com',
    iosClientId: '183778840538-5hp72iqfkaldtpfajro93un4f791qjnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayna',
  );
}
